// import type { Metadata } from "next";



//  const Metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import Head from 'next/head';

const Metadata = () => (
  <Head>
    <title>My Website</title>
    <meta name="description" content="This is my website" />
    {/* Aap jo bhi metadata add karna chahein wo yahan add kar sakte hain */}
  </Head>
);

export default Metadata